In [1]:
import numpy as np
#RANDOM MODULE IS SUB-PACKAGE OF NUMPY

In [2]:
A = np.random.rand(1)
print(A)


[0.729708]


In [3]:
A = np.random.rand(8,4) #rand-rang is  between 0 and 1
print(A)

[[0.38315778 0.81905066 0.45479437 0.87924144]
 [0.83447402 0.11355606 0.24094638 0.72582544]
 [0.41870981 0.19754043 0.52074526 0.79898356]
 [0.81362647 0.55279386 0.21231923 0.29356624]
 [0.10611795 0.87420055 0.956617   0.88314775]
 [0.57945353 0.90224413 0.26266913 0.49437277]
 [0.49981806 0.3211994  0.7707084  0.36287041]
 [0.01672133 0.17953419 0.74702733 0.4298443 ]]


In [4]:
A = 10*np.random.rand(8,4) #rand range is between 0 and 1
print(A)


[[1.62261279 0.8218882  9.29132018 0.20942133]
 [8.89000766 0.61881948 0.47112421 3.1954284 ]
 [5.7745116  7.98448904 3.90155826 8.42544355]
 [2.01685866 6.30791959 4.28562322 5.22432085]
 [4.06199664 1.21635883 2.09548229 0.53290271]
 [7.25383761 1.47127667 7.34514291 6.15956982]
 [5.56847693 5.94147841 0.68788034 8.8945425 ]
 [5.08817579 9.4142525  8.96497475 0.87631205]]


In [5]:
A = np.floor(10*np.random.rand(8,4))
print(A)

[[2. 0. 9. 0.]
 [1. 4. 2. 6.]
 [8. 5. 1. 3.]
 [5. 8. 9. 6.]
 [4. 2. 9. 3.]
 [8. 4. 6. 3.]
 [9. 1. 5. 6.]
 [5. 9. 7. 4.]]


In [6]:
A = np.arange(1,33).reshape(8,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [7]:
np.vsplit(A,4) #vsplit split the array from top to bottom

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [8]:
np.vsplit(A,(3,5)) #split it after third-row and fifth-row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [9]:
a = np.arange(1,33).reshape(4,8)
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [10]:
#Create an array with 4rows and 8columns
np.hsplit(a,4) #spliting takes from left to right

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [11]:
np.hsplit(a,(3,7)) #spliting takes after 3rd column and 7th column

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

In [12]:
np.hsplit(a,(2,5))

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4,  5],
        [11, 12, 13],
        [19, 20, 21],
        [27, 28, 29]]),
 array([[ 6,  7,  8],
        [14, 15, 16],
        [22, 23, 24],
        [30, 31, 32]])]

Trignometry

In [13]:
np.pi

3.141592653589793

In [14]:
A= [np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [15]:
B=np.rad2deg(A) #convert radians to degrees

In [16]:
np.deg2rad(B)

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [17]:
np.sin(1)

0.8414709848078965

In [18]:
np.cos(1)

0.5403023058681398

In [19]:
np.tan(1)

1.5574077246549023

Statistics

In [20]:
st=np.array([23,45,67,89,21,34])

In [21]:
np.mean(st)

46.5

In [22]:
np.median(st)

39.5

In [23]:
np.std(st) #standard deviation

24.452334585202017

In [24]:
np.var(st)

597.9166666666666

In [25]:
C = np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [26]:
np.linalg.inv(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [27]:
C = 10*np.random.rand(24).reshape(6,4)
print(C)

[[5.21743441 5.50500222 1.21173876 7.09398197]
 [0.46492966 1.49917543 0.06927596 3.25313072]
 [4.79558325 1.23831298 7.74527895 0.30306742]
 [2.65643289 6.33658262 2.96227169 3.06767719]
 [3.10611097 1.05227827 8.89767243 3.80914338]
 [5.74950436 2.31569536 6.3573968  9.57306406]]


In [28]:
print(np.argmax(C)) #random value

23


In [29]:
print(np.argmax(C,axis = 1)) #rows wise

[3 3 2 1 2 3]


In [30]:
print (np.argmax(C,axis=0)) #column wise

[5 3 4 5]


In [31]:
print (np.argmin(C))

6


In [32]:
print(np.argmin(C,axis=0))

[1 4 1 2]


In [33]:
print(np.argmin(C,axis=1))

[2 2 3 0 1 1]


Searching

In [34]:
a = np.array([34,56,7,17,88,91]) #output=[0,1,4]
print(np.where(a%2 == 0)) #array([0,1,4],dtype=int64),)
 #used only for already stored list
a = np.array([6,7,8,9,10])

(array([0, 1, 4]),)


In [35]:
a = np.array([24,16,7,17,54,60])
print(np.where(a%6==0))

(array([0, 4, 5]),)


In [36]:
a=np.array([6,7,8,9,10])
x=np.searchsorted(a,7)
print(x)

1


In [37]:
a=np.array([1,8,5,10])
x=np.searchsorted(a,5)
print(x)

1


In [38]:
#sorting array
import numpy as np
arr = np.array(['banana','apple','guava'])
print(np.sort(arr))

['apple' 'banana' 'guava']


In [ ]:
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


In [39]:
#2d sorting happens within row
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


Filtering

In [40]:
arr = np.array([40,43,50,44,67,78]) #filtering may be an array/list
flit=np.where(arr%2== 0)
print(flit)

(array([0, 2, 3, 5]),)


In [41]:
arr[flit]

array([40, 50, 44, 78])

Iterating to 2arrays

In [42]:
names = np.array(["Susmi","Lilly","Minni"])
initials = np.array(["U","M","D"])
for i,j in zip(initials,names):
  print(i,".",j)

U . Susmi
M . Lilly
D . Minni


In [43]:
a1=np.array([10,20,30,50,70])
a2=np.array([22,44,77,99,66])
n = np.divide(a1,a2)
print(n)

[0.45454545 0.45454545 0.38961039 0.50505051 1.06060606]


In [44]:
a1=np.array([11,32,54,61,32])
a2=np.array([43,57,68,98,43])
n = np.mod(a1,a2)
print(n)

[11 32 54 61 32]


In [45]:
a1=np.array([47,92,67,32])
a2=np.array([87,32,78,64])
n=np.divmod(a1,a2)
print(n)

(array([0, 2, 0, 0]), array([47, 28, 67, 32]))


In [46]:
a1=np.array([75,36,67,33])
a2=np.array([34,67,98,21])
n=np.multiply(a1,a2)
print(n)

[2550 2412 6566  693]


Logarithms

In [47]:
a1 = np.arange(1,10)
print(a1)
print(np.log2(a1)) #base2

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [48]:
a = 3.2
print(np.log(a)) #natural log e

1.1631508098056809


In [49]:
a = np.array([1,2,3,4])
print(np.log(a)) #natural log e

[0.         0.69314718 1.09861229 1.38629436]


In [50]:
a = 1.2
print(np.log2(a)) #log base 2

0.2630344058337938


In [51]:
a = 1.2
print(np.log10(a)) #log base 10

0.07918124604762482


Other mathematical fuctions

In [52]:
a2 = np.array([5,6,7,1])
x = np.cumprod(a2)
print(x)

[  5  30 210 210]


In [53]:
a1 = np.array([23,34,3,2,])
x = np.cumsum(a1)
print(x)

[23 57 60 62]


In [54]:
a1 = np.array([12,24,35,11]) #e2-e1
newarr = np.diff(a1)
print(newarr)

[ 12  11 -24]


In [55]:
num1=455
num2=665
x = np.lcm(num1,num2)
print(x)

8645


In [56]:
num1=667
num2=887
x = np.gcd(num1,num2)
print(x)

1


In [57]:
a = np.array([12,15,16])
gcd = np.gcd.reduce(a) #takes multiple inputs gives single output
print(gcd)

1


In [58]:
a = np.array([12,15,16])
lc = np.gcd.reduce(a) #takes multiple inputs gives single output
print(lc)

1


In [59]:
a = np.array([12,15,16])
hc = np.gcd.reduce(a) #takes multiple inputs gives single output
print(hc)

1
